### 01 -
POST http://localhost:3333/user/singUp
Content-Type: application/json

{
  "first_name":"Gabriel",
  "last_name": "Silva",
  "email": "gabriel@gmail.com.br"
}

### 02 -
POST http://localhost:3333/purchase/gabriel@gmail.com.br?date=10/11/2022
Content-Type: application/json

[
  {
    "id_product": 1,
    "qty_product_selected": 2
  },
  {
    "id_product": 2,
    "qty_product_selected": 3
  }
]

### 3- get de todos os produtos
GET http://localhost:3333/products/all/1
